### ISSUE TITLE
Error en la documentacion de SimpleNLG-es

### ISSUE THREAD

**Issue by lluisp** [citiususc/SimpleNLG-ES#2]
En la pagina
https://github.com/citiususc/SimpleNLG-ES/wiki/Secci%C3%B3n-II-%E2%80%93-Qui%C3%A9n-puede-usar-SimpleNLG-es
se menciona que el uso del lexicon español de FreeLing esta sujeto a una licencia restrictiva. Aunque no se menciona cual, entiendo que presupone que es la licencia de todo el paquete.
Eso no es asi.  
Tal como se indica en el fichero COPYING (https://github.com/TALP-UPC/FreeLing/blob/master/COPYING): 
    Spanish dictionary contained in the files in data/es/dictionary
     (this package) and share/es/dicc.src (after installation) is
     extracted from the Spanish Resource Grammar projects
     (http://www.upf.edu/pdi/iula/montserrat.marimon/srg.html) and was
     developed at the Institut Universitari de Linguistica Aplicada
     (http://www.iula.upf.edu) of the Universitat Pompeu Fabra. It is
     distributed under a "Lesser General Public License For Linguistic
     Resources" license. You'll find the license in the file
     LICENSES/LGPLLR.license included in this package or at
     http://sanskrit.inria.fr/DATA/LGPLLR.html

La LGPLLR es mucho menos restrictiva que la GPL, y permite su uso en productos comerciales, si las mejoras al lexicon (en caso de haberlas) se hacen publicas.

**Comment by elbugari** [comment]
Muchas gracias por tu apunte, Lluis. Corregiremos esto que nos indicas, para incluir un enlace al fichero COPYING de Freeling.

**Comment by lluisp** [comment]
Ya veo que habeis puesto el enlace ala licencia del diccionario.  Quiza estaria bien añadir una frase diciendo "para mas detalles, ver el fichero COPYING de freeling", con un enlace al fichero.
https://github.com/TALP-UPC/FreeLing/blob/master/COPYING
gracias!

**Comment by wanobros** [comment]
> 
> 
> Ya veo que habeis puesto el enlace ala licencia del diccionario. Quiza estaria bien añadir una frase diciendo "para mas detalles, ver el fichero COPYING de freeling", con un enlace al fichero.
> https://github.com/TALP-UPC/FreeLing/blob/master/COPYING
> gracias!

Gracias Lluis, el enlace al fichero también lo incluimos, pero está en la [sección IV de la Wiki](https://github.com/citiususc/SimpleNLG-ES/wiki/Secci%C3%B3n-IV-%E2%80%93-Lexic%C3%B3n). Como está dedicada al lexicón, creímos que tenía más sentido dar más información al respecto ahí.

**Comment by lluisp** [comment]
ok!
